---

- name: Create eula.txt
  ansible.builtin.copy:
    content: "eula=true"
    dest: "{{ minecraft_server }}/eula.txt"
    owner: minecraft
    group: minecraft

- name: Create start_server.sh
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      /usr/bin/tmux new-session -s minecraft -c "/opt/minecraft/server" -d
      tmux send-keys -t minecraft "/usr/bin/java -Xms{{ java_Xms }} -Xmx{{ java_Xmx }} {{ java_flags }} -jar minecraft_server-{{ minecraft_version }}.jar nogui" ENTER
    dest: "{{ minecraft_scripts }}/start_server.sh"
    mode: "a+x"
    owner: minecraft
    group: minecraft

- name: Create stop_server.sh
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      /usr/bin/tmux send-keys -t minecraft /save-all ENTER
      sleep 15
      /usr/bin/tmux send-keys -t minecraft /stop ENTER
      sleep 15
      /usr/bin/tmux kill-session -t minecraft
    dest: "{{ minecraft_scripts }}/stop_server.sh"
    mode: "a+x"
    owner: minecraft
    group: minecraft

- name: Create minecraft systemd service file
  ansible.builtin.template:
    src: "minecraft.service.j2"
    dest: "/lib/systemd/system/minecraft.service"
